apiVersion: v1
kind: Namespace
metadata:
  name: coroot

---
apiVersion: v1
kind: Service
metadata:
  name: coroot
  namespace: coroot
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: coroot

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coroot-pvc
  namespace: coroot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coroot
  name: coroot
  namespace: coroot
spec:
  selector:
    matchLabels:
      app: coroot
  template:
    metadata:
      labels:
        app: coroot
    spec:
      containers:
        - name: coroot
          image: ghcr.io/coroot/coroot:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
          volumeMounts:
            - mountPath: /data
              name: coroot-pv
      volumes:
        - name: coroot-pv
          persistentVolumeClaim:
            claimName: coroot-pvc
