# -----------------------------------
# Namespace Definition
# -----------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: codexray

---
# -----------------------------------
# PersistentVolumeClaim Definition
# -----------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codexray-pvc
  namespace: codexray
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path

---
# -----------------------------------
# Service Definition
# -----------------------------------
apiVersion: v1
kind: Service
metadata:
  name: codexray
  namespace: codexray
spec:
  selector:
    app: codexray
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  type: LoadBalancer

---
# -----------------------------------
# Deployment Definition
# -----------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codexray
  namespace: codexray
  labels:
    app: codexray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codexray
  template:
    metadata:
      labels:
        app: codexray
    spec:
      containers:
      - name: codexray
        image: $DOCKERHUB_USERNAME/codexray:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
          - mountPath: /data
            name: codexray-pv
      volumes:
        - name: codexray-pv
          persistentVolumeClaim:
            claimName: codexray-pvc
